# Generated by Django 3.2.3 on 2021-05-28 06:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cat_image', models.ImageField(blank=True, help_text='Please upload png and jpg images', null=True, upload_to='images/cat_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_desc', models.CharField(max_length=500)),
                ('ad_price', models.IntegerField(blank=True, null=True)),
                ('ad_image1', models.ImageField(blank=True, null=True, upload_to='images/ad_images/')),
                ('ad_image2', models.ImageField(blank=True, null=True, upload_to='images/ad_images/')),
                ('ad_image3', models.ImageField(blank=True, null=True, upload_to='images/ad_images/')),
                ('ad_postedon', models.DateTimeField(default=datetime.datetime.now)),
                ('ad_phoneno', models.BigIntegerField(blank=True, null=True)),
                ('ad_status', models.IntegerField(blank=True, default=1, null=True)),
                ('ad_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uplistold.category')),
                ('ad_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uplistold.location')),
                ('ad_postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
