# Generated by Django 3.2.3 on 2021-06-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplistold', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/default.png', null=True, upload_to='images/profile/'),
        ),
    ]
